export const ALL_VIDEO_REQUEST = "ALL_VIDEO_REQUEST";
export const ALL_VIDEO_SUCCESS = "ALL_VIDEO_SUCCESS";
export const ALL_VIDEO_FAIL = "ALL_VIDEO_FAIL";


export const DELETE_VIDEO_REQUEST = "DELETE_VIDEO_REQUEST";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_RESET = "DELETE_VIDEO_RESET";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";



export const NEW_VIDEO_REQUEST = "NEW_VIDEO_REQUEST";
export const NEW_VIDEO_SUCCESS = "NEW_VIDEO_SUCCESS";
export const NEW_VIDEO_RESET = "NEW_VIDEO_RESET";
export const NEW_VIDEO_FAIL = "NEW_VIDEO_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";